In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv('adult.csv')

In [4]:
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [5]:
df.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [6]:
df.replace('?',np.nan,inplace=True)

In [7]:
df.dtypes

age                 int64
workclass          object
fnlwgt              int64
education          object
educational-num     int64
marital-status     object
occupation         object
relationship       object
race               object
gender             object
capital-gain        int64
capital-loss        int64
hours-per-week      int64
native-country     object
income             object
dtype: object

In [8]:
df.isnull().sum()

age                   0
workclass          2799
fnlwgt                0
education             0
educational-num       0
marital-status        0
occupation         2809
relationship          0
race                  0
gender                0
capital-gain          0
capital-loss          0
hours-per-week        0
native-country      857
income                0
dtype: int64

In [10]:
df = df.drop(['workclass','occupation','native-country','fnlwgt','relationship','race'],axis=1)

In [11]:
df.head()

,age,education,educational-num,marital-status,gender,capital-gain,capital-loss,hours-per-week,income
0,25,11th,7,Never-married,Male,0,0,40,<=50K
1,38,HS-grad,9,Married-civ-spouse,Male,0,0,50,<=50K
2,28,Assoc-acdm,12,Married-civ-spouse,Male,0,0,40,>50K
3,44,Some-college,10,Married-civ-spouse,Male,7688,0,40,>50K
4,18,Some-college,10,Never-married,Female,0,0,30,<=50K

In [12]:
df.dtypes

age                 int64
education          object
educational-num     int64
marital-status     object
gender             object
capital-gain        int64
capital-loss        int64
hours-per-week      int64
income             object
dtype: object

In [13]:
df.isnull().sum()

age                0
education          0
educational-num    0
marital-status     0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
income             0
dtype: int64

In [14]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
encoder = OneHotEncoder(sparse_output=False)

In [17]:
encoded = encoder.fit_transform(df[['education','marital-status','gender','capital-gain','capital-loss','hours-per-week']])

In [19]:
encoded_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out(['education','marital-status','gender','capital-gain','capital-loss','hours-per-week']))

In [20]:
df = df.join(encoded_df)

In [22]:
df = df.drop(['education','marital-status','gender','capital-gain','capital-loss','hours-per-week'],axis=1)

In [23]:
df.head()

,age,educational-num,income,education_10th,education_11th,education_12th,education_1st-4th,education_5th-6th,education_7th-8th,education_9th,...,hours-per-week_89,hours-per-week_90,hours-per-week_91,hours-per-week_92,hours-per-week_94,hours-per-week_95,hours-per-week_96,hours-per-week_97,hours-per-week_98,hours-per-week_99
0,25,7,<=50K,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,38,9,<=50K,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,28,12,>50K,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,44,10,>50K,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,18,10,<=50K,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
df.tail()

,age,educational-num,income,education_10th,education_11th,education_12th,education_1st-4th,education_5th-6th,education_7th-8th,education_9th,...,hours-per-week_89,hours-per-week_90,hours-per-week_91,hours-per-week_92,hours-per-week_94,hours-per-week_95,hours-per-week_96,hours-per-week_97,hours-per-week_98,hours-per-week_99
48837,27,12,<=50K,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48838,40,9,>50K,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48839,58,9,<=50K,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48840,22,9,<=50K,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48841,52,9,>50K,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
X = df.drop(['income'],axis=1)

In [38]:
y = df['income']

In [39]:
y = y.map({'<=50K': 0, '>50K': 1})

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2)

In [42]:
from sklearn.naive_bayes import GaussianNB

In [43]:
model = GaussianNB()

In [44]:
df.isnull().sum()

age                  0
educational-num      0
income               0
education_10th       0
education_11th       0
                    ..
hours-per-week_95    0
hours-per-week_96    0
hours-per-week_97    0
hours-per-week_98    0
hours-per-week_99    0
Length: 346, dtype: int64

In [45]:
model.fit(X_train, y_train)

GaussianNB()

In [46]:
print(y.isnull().sum())  # Check for missing values in y

0